#!/bin/bash
# GETTING-STARTED: change 'db.sqlite3' to your sqlite3 database:

if [ ! -f $OPENSHIFT_DATA_DIR/db.sqlite3 ]
then
	echo "Copying $OPENSHIFT_REPO_DIR/db.sqlite3 to $OPENSHIFT_DATA_DIR"
	cp "$OPENSHIFT_REPO_DIR"db.sqlite3 $OPENSHIFT_DATA_DIR
fi

echo "Executing 'python $OPENSHIFT_REPO_DIR/manage.py migrate --noinput'"
python "$OPENSHIFT_REPO_DIR"manage.py migrate --noinput

echo "Executing 'python $OPENSHIFT_REPO_DIR/ loaddata images _3caassurance'"
python "$OPENSHIFT_REPO_DIR"manage.py loaddata user images _3caassurance

echo "Executing 'python $OPENSHIFT_REPO_DIR/manage.py update_index'"
python "$OPENSHIFT_REPO_DIR"manage.py update_index

echo "Executing 'python $OPENSHIFT_REPO_DIR/manage.py compilemessages -l fr'"
python "$OPENSHIFT_REPO_DIR"manage.py compilemessages -l fr

# Create media folder and change permission
MEDIA_DIR=$OPENSHIFT_DATA_DIR/media
REPO_MEDIA_DIR=$OPENSHIFT_REPO_DIR/media
chmod -R o+rw $REPO_MEDIA_DIR
if [ ! -d $MEDIA_DIR ]; then
mkdir $MEDIA_DIR
fi
# Create symlink to media folder
ln -sf $MEDIA_DIR $REPO_MEDIA_DIR

# Create static folder and change permission
STATIC_DIR=$OPENSHIFT_DATA_DIR/static
REPO_STATIC_DIR=$OPENSHIFT_REPO_DIR/static
# Create static files folder and change permission
if [ ! -d $REPO_STATIC_DIR ]; then
mkdir $REPO_STATIC_DIR
chmod -R o+rw $REPO_STATIC_DIR
fi
chmod -R o+rw $REPO_STATIC_DIR
# Create symlink to static folder
ln -sf $STATIC_DIR $REPO_STATIC_DIR

STATIC_FILES_DIR=$OPENSHIFT_DATA_DIR/staticfiles
REPO_STATIC_FILES_DIR=$OPENSHIFT_REPO_DIR/_3caassurance/static
if [ ! -d $STATIC_FILES_DIR ]; then
mkdir $STATIC_FILES_DIR
fi
# Create symlink to static files folder
ln -sf $STATIC_FILES_DIR $REPO_STATIC_FILES_DIR
