#!/bin/bash

PYTHON=$VIRTUAL_ENV/bin/python
PIP=$VIRTUAL_ENV/bin/pip2.7
PIP_CACHE_DIR=$OPENSHIFT_DATA_DIR/.cache


# Create static folder and change permission
if [ ! -d $PIP_CACHE_DIR ]; then
mkdir $PIP_CACHE_DIR
chmod -R o+rw $OPENSHIFT_REPO_DIR/.cache
fi

# Update pip and install dependencies
source $VIRTUAL_ENV/bin/activate
$PIP install --upgrade pip && $PIP install -r $OPENSHIFT_REPO_DIR/requirements.txt
deactivate
