#!/bin/bash

PROJECT_NAME="_3caassurance"

PROJECT_DIR=$OPENSHIFT_REPO_DIR
VIRTUALENV_DIR=$VIRTUAL_ENV

PYTHON=$OPENSHIFT_PYTHON_DIR/bin/python
PIP=$OPENSHIFT_PYTHON_DIR/bin/pip


# Create database
sqlite3 $PROJECT_NAME

echo $PROJECT_DIR > $VIRTUALENV_DIR/.project

# Run migrate/update_index/load_initial_data
$PYTHON $PROJECT_DIR/manage.py migrate --noinput && \
$PYTHON $PROJECT_DIR/manage.py loaddata images _3caassurance && \
$PYTHON $PROJECT_DIR/manage.py update_index && \
$PYTHON $PROJECT_DIR/manage.py compilemessages -l fr
