#!/bin/bash

PROJECT_NAME="_3caassurance"

PROJECT_DIR=$OPENSHIFT_REPO_DIR
VIRTUALENV_DIR=$VIRTUAL_ENV

PYTHON=$OPENSHIFT_PYTHON_DIR/bin/python
PIP=$OPENSHIFT_PYTHON_DIR/bin/pip


# Create database
createdb $PROJECT_NAME

echo $PROJECT_DIR > $VIRTUALENV_DIR/.project


# Install PIP requirements
sudo -H $PIP install --upgrade pip
sudo -H $PIP install -r $PROJECT_DIR/requirements.txt -f $OPENSHIFT_HOMEDIR/wheelhouse


# Set execute permissions on manage.py as they get lost if we build from a zip file
chmod a+x $PROJECT_DIR/manage.py


# Run migrate/update_index/load_initial_data
$PYTHON $PROJECT_DIR/manage.py migrate --noinput && $PYTHON $PROJECT_DIR/manage.py loaddata images _3caassurance &&  $PYTHON $PROJECT_DIR/manage.py update_index && $PYTHON $PROJECT_DIR/manage.py compilemessages -l fr"


# Add a couple of aliases to manage.py into .bashrc
cat << EOF >> $OPENSHIFT_HOMEDIR/.bashrc
export PYTHONPATH=$PROJECT_DIR
export DJANGO_SETTINGS_MODULE=$PROJECT_NAME.settings.prod

alias dj="django-admin"
alias djrun="dj runserver 0.0.0.0:$OPENSHIFT_PYTHON_PORT"

source $VIRTUALENV_DIR/bin/activate
cd $PROJECT_DIR
EOF
