#!/bin/bash

PROJECT_NAME="_3caassurance"

PROJECT_DIR=$OPENSHIFT_REPO_DIR

PYTHON=$VIRTUAL_ENV/bin/python

# Create database
sqlite3 $PROJECT_NAME

echo $PROJECT_DIR > $VIRTUALENV/.project

# Run migrate/update_index/load_initial_data
$PYTHON "$OPENSHIFT_REPO_DIR"manage.py migrate --noinput && \
$PYTHON "$OPENSHIFT_REPO_DIR"manage.py loaddata images _3caassurance && \
$PYTHON "$OPENSHIFT_REPO_DIR"manage.py update_index && \
$PYTHON "$OPENSHIFT_REPO_DIR"manage.py compilemessages -l fr
