= 3caassurance
:hardbreaks:

== Requirements
Python 2.7

== Install work environment
If virtualenv is not installed
`pip install virtualenv`

Create virtualenv
`virtualenv venv`

Install dependencies
`pip install -r requirements.txt`

== Launch locally
Install migration scripts
`python manage.py migrate`

If admin account is not created
`python manage.py createsuperuser` (admin, changeme)

Start the server
`python manage.py runserver`

Deployed on `http://127.0.0.1:8000/`
Admin page accessible at `http://127.0.0.1:8000/admin/`

== Launch with vagrant
`vagrant up --provision`
`vagrant ssh`
In the VM
`./manage.py runserver 0.0.0.0:8000`

== I18N
Add I18N key and translations to `locale/fr/LC_MESSAGES/django.po`
Once done, `python manage.py compilemessages -l fr`
This is automatically done when using the Vagrant configuration

== Updating the migration files
`./manage.py dumpdata auth.user --natural-foreign --indent 2 > _3caassurance/fixtures/user.json`
`./manage.py dumpdata wagtailimages.image --natural-foreign --indent 2 > _3caassurance/fixtures/images.json`
`./manage.py dumpdata -e auth.permission -e contenttypes.contenttype -e wagtailimages.image -e sessions.session --natural-foreign --indent 2 > _3caassurance/fixtures/_3caassurance.json`

== Set pip cache directory for openshift before deployment
sudo rhc env set PIP_DOWNLOAD_CACHE="$OPENSHIFT_DATA_DIR/.cache" -a 3caassurance
