# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('_3caassurance', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGalleryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField([(b'image', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'caption', wagtail.wagtailcore.blocks.TextBlock('title')), (b'title', wagtail.wagtailcore.blocks.RichTextBlock())], icon='image', label='Photo'))])),
            ],
            options={
                'verbose_name': 'Gallerie Photos',
            },
            bases=('wagtailcore.page',),
        ),
    ]
