# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 20:00
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('_3caassurance', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': '3CA Assurance'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='products',
            field=wagtail.wagtailcore.fields.StreamField([(b'product', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'caption', wagtail.wagtailcore.blocks.RichTextBlock())], icon='pilcrow', label='Product'))], default=None),
            preserve_default=False,
        ),
    ]
